spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${emailSender}
    password: ${emailSenderPassword}
    protocol: 'smtp'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


company-data:
  name: 'companyName'
  Email: 'companyEmail@info.com'
  tel: '+4900000000'
  web: 'www.company-web.com'

jwt-data:
  secret: ${secret}
  expireTime: 300000
  refreshTokenTime: 86400000
emailSenderData:
  cc: 'baraa.test.com'
  subject: 'Please active your account'